const DEFAULT_CONFIG={API_URL:'',API_TOKEN:'',DEVICE_START:1,DEVICE_END:8,GATEWAY_LAT:3.341264,GATEWAY_LON:-76.529448,MAP_ZOOM:17,JOIN_TIMEOUT_MS:45000,LINKCHECK_TIMEOUT_MS:25000};
const CONFIG={...DEFAULT_CONFIG,...(window.LFL_CONFIG||{})};
const NUS_SERVICE='6e400001-b5a3-f393-e0a9-e50e24dcca9e';
const NUS_RX='6e400002-b5a3-f393-e0a9-e50e24dcca9e';
const NUS_TX='6e400003-b5a3-f393-e0a9-e50e24dcca9e';
const IDW_CONFIG={cellSizePx:14,power:2,maxInfluenceMeters:145,minOpacity:.16,maxOpacity:.62,maxRadiusPaddingMeters:30};
let bleDevice=null,bleRxChar=null,bleTxChar=null,rxBuffer='',joinState=-1,measuring=false;
let waiters=[],pointsLayer=null,idwLayer=null,map=null;
const enc=new TextEncoder(),dec=new TextDecoder(),$=id=>document.getElementById(id);
const els={deviceSelect:$('deviceSelect'),connect:$('connectBtn'),disconnect:$('disconnectBtn'),retry:$('retryJoinBtn'),take:$('takeSampleBtn'),ble:$('bleStatus'),join:$('joinStatus'),gps:$('gpsStatus'),api:$('apiStatus'),process:$('processStatus'),log:$('log'),lastRssi:$('lastRssi'),lastSnr:$('lastSnr'),lastGw:$('lastGw'),lastPayload:$('lastPayload'),lastAccuracy:$('lastAccuracy'),mapTitle:$('mapTitle'),empty:$('emptyMapMsg'),table:$('pointsTable'),configWarning:$('configWarning')};

function setStatus(el,text,kind=''){el.textContent=text;el.className='status'+(kind?' '+kind:'');}
function log(msg){els.log.textContent+='['+new Date().toLocaleTimeString()+'] '+msg+'\n';els.log.scrollTop=els.log.scrollHeight;}
function deviceList(){const out=[];for(let i=Number(CONFIG.DEVICE_START);i<=Number(CONFIG.DEVICE_END);i++)out.push('Dev-'+String(i).padStart(2,'0'));return out;}
function selectedDevice(){return els.deviceSelect.value;}
function devNumber(dev){return Number(String(dev).replace('Dev-',''));}
function setProcess(text,kind=''){setStatus(els.process,text,kind);}
function setJoined(value){joinState=value;if(value===1){setStatus(els.join,'Unido a TTN','ok');els.retry.classList.add('hidden');}else if(value===0){setStatus(els.join,'No unido','bad');els.retry.classList.remove('hidden');}else{setStatus(els.join,'Sin verificar','warn');els.retry.classList.add('hidden');}refreshActionState();}
function refreshActionState(){els.take.disabled=!(bleRxChar&&joinState===1&&!measuring);}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function initDevices(){els.deviceSelect.innerHTML='';for(const dev of deviceList()){const opt=document.createElement('option');opt.value=dev;opt.textContent=dev;els.deviceSelect.appendChild(opt);}const remembered=localStorage.getItem('lfl-device');if(remembered&&deviceList().includes(remembered))els.deviceSelect.value=remembered;}
function safeInvalidate(){if(!map)return;requestAnimationFrame(()=>{map.invalidateSize(false);idwLayer&&idwLayer.redraw();setTimeout(()=>{map.invalidateSize(false);idwLayer&&idwLayer.redraw();},180);setTimeout(()=>{map.invalidateSize(false);idwLayer&&idwLayer.redraw();},600);});}
function distanceMeters(aLat,aLon,bLat,bLon){const R=6371000,toRad=d=>d*Math.PI/180;const dLat=toRad(bLat-aLat),dLon=toRad(bLon-aLon),lat1=toRad(aLat),lat2=toRad(bLat);const h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function rssiToColor(rssi,alpha){let r,g,b;if(rssi>=-85){r=34;g=197;b=94;}else if(rssi>=-100){const t=(rssi+100)/15;r=Math.round(250-(216*t));g=Math.round(204-(7*t));b=Math.round(21+(73*t));}else if(rssi>=-112){const t=(rssi+112)/12;r=Math.round(239+11*t);g=Math.round(68+136*t);b=Math.round(68-47*t);}else{r=185;g=28;b=28;}return `rgba(${r},${g},${b},${alpha})`;}
function makeIdwLayer(){return L.Layer.extend({initialize(opts={}){this.options=opts;this.points=[];},onAdd(map){this._map=map;this._canvas=L.DomUtil.create('canvas','leaflet-idw-layer');this._canvas.style.position='absolute';this._canvas.style.pointerEvents='none';this._canvas.style.zIndex='350';map.getPanes().overlayPane.appendChild(this._canvas);map.on('moveend zoomend resize viewreset',this.redraw,this);this.redraw();},onRemove(map){map.off('moveend zoomend resize viewreset',this.redraw,this);this._canvas.remove();},setPoints(points){this.points=points||[];this.redraw();},redraw(){if(!this._map||!this._canvas)return;const size=this._map.getSize();this._canvas.width=size.x;this._canvas.height=size.y;const topLeft=this._map.containerPointToLayerPoint([0,0]);L.DomUtil.setPosition(this._canvas,topLeft);const ctx=this._canvas.getContext('2d');ctx.clearRect(0,0,size.x,size.y);if(this.points.length===0)return;const gw={lat:CONFIG.GATEWAY_LAT,lon:CONFIG.GATEWAY_LON};let maxRadius=0;const pts=this.points.map(p=>({lat:Number(p.lat),lon:Number(p.lon),rssi:Number(p.rssi)})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Number.isFinite(p.rssi));if(!pts.length)return;for(const p of pts)maxRadius=Math.max(maxRadius,distanceMeters(gw.lat,gw.lon,p.lat,p.lon));maxRadius+=IDW_CONFIG.maxRadiusPaddingMeters;const cell=IDW_CONFIG.cellSizePx;for(let y=0;y<size.y;y+=cell){for(let x=0;x<size.x;x+=cell){const ll=this._map.containerPointToLatLng([x+cell/2,y+cell/2]);const dGw=distanceMeters(gw.lat,gw.lon,ll.lat,ll.lng);if(dGw>maxRadius)continue;let num=0,den=0,nearest=Infinity,count=0;for(const p of pts){const d=Math.max(1,distanceMeters(ll.lat,ll.lng,p.lat,p.lon));if(d>IDW_CONFIG.maxInfluenceMeters)continue;const w=1/(d**IDW_CONFIG.power);num+=p.rssi*w;den+=w;nearest=Math.min(nearest,d);count++;}if(!den)continue;const rssi=num/den;const nearFactor=Math.max(0,1-nearest/IDW_CONFIG.maxInfluenceMeters);const densityFactor=Math.min(1,count/3);const alpha=IDW_CONFIG.minOpacity+(IDW_CONFIG.maxOpacity-IDW_CONFIG.minOpacity)*Math.max(.25,nearFactor)*Math.max(.55,densityFactor);ctx.fillStyle=rssiToColor(rssi,alpha);ctx.fillRect(x,y,cell+1,cell+1);}}}});}
function initMap(){const center=[CONFIG.GATEWAY_LAT,CONFIG.GATEWAY_LON];map=L.map('map',{zoomControl:true,dragging:false,touchZoom:true,scrollWheelZoom:false,doubleClickZoom:true,boxZoom:false,keyboard:false,tap:false,preferCanvas:true}).setView(center,CONFIG.MAP_ZOOM);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,keepBuffer:4,updateWhenIdle:false,attribution:'&copy; OpenStreetMap'}).addTo(map);L.marker(center,{title:'Gateway Icesi'}).addTo(map).bindPopup('<b>Gateway Icesi</b><br>Referencia de la práctica');pointsLayer=L.layerGroup().addTo(map);idwLayer=new (makeIdwLayer())();idwLayer.addTo(map);new ResizeObserver(safeInvalidate).observe($('map'));safeInvalidate();}
function fmtTime(iso){try{return new Date(iso).toLocaleString();}catch{return iso||'';}}
function renderPoints(points){pointsLayer.clearLayers();idwLayer&&idwLayer.setPoints(points);els.table.innerHTML='';els.mapTitle.textContent='Mapa de cobertura estimada '+selectedDevice();if(!points.length){els.empty.classList.remove('hidden');map.setView([CONFIG.GATEWAY_LAT,CONFIG.GATEWAY_LON],CONFIG.MAP_ZOOM,{animate:false});safeInvalidate();return;}els.empty.classList.add('hidden');const valid=[];for(const p of points){const lat=Number(p.lat),lon=Number(p.lon),rssi=Number(p.rssi),snr=Number(p.snr);if(Number.isFinite(lat)&&Number.isFinite(lon)&&Number.isFinite(rssi)){valid.push([lat,lon]);L.circleMarker([lat,lon],{radius:6,weight:2,color:'#0284c7',fillColor:'#0ea5e9',fillOpacity:.9}).bindPopup(`<b>${escapeHtml(selectedDevice())}</b><br>RSSI: ${rssi} dBm<br>SNR: ${snr} dB<br>GW: ${escapeHtml(p.gw_count)}<br>Payload: ${escapeHtml(p.payload)}<br>${escapeHtml(fmtTime(p.timestamp))}`).addTo(pointsLayer);}}const bounds=L.latLngBounds([[CONFIG.GATEWAY_LAT,CONFIG.GATEWAY_LON],...valid]);if(bounds.isValid())map.fitBounds(bounds.pad(.20),{maxZoom:18,animate:false});safeInvalidate();for(const p of points.slice(-25).reverse()){const tr=document.createElement('tr');tr.innerHTML=`<td>${escapeHtml(fmtTime(p.timestamp))}</td><td>${escapeHtml(p.rssi)}</td><td>${escapeHtml(p.snr)}</td><td>${escapeHtml(p.gw_count)}</td><td>${escapeHtml(p.payload)}</td><td>${escapeHtml(Number(p.lat).toFixed(6))}</td><td>${escapeHtml(Number(p.lon).toFixed(6))}</td>`;els.table.appendChild(tr);}}
function jsonp(params,timeoutMs=12000){return new Promise((resolve,reject)=>{if(!CONFIG.API_URL){reject(new Error('API_URL no configurada'));return;}const cb='lfl_cb_'+Math.random().toString(36).slice(2);const url=new URL(CONFIG.API_URL);for(const[k,v]of Object.entries(params))url.searchParams.set(k,v==null?'':String(v));if(CONFIG.API_TOKEN)url.searchParams.set('token',CONFIG.API_TOKEN);url.searchParams.set('callback',cb);const script=document.createElement('script');const timer=setTimeout(()=>cleanup(new Error('Timeout API')),timeoutMs);function cleanup(err,data){clearTimeout(timer);delete window[cb];script.remove();err?reject(err):resolve(data);}window[cb]=data=>cleanup(null,data);script.onerror=()=>cleanup(new Error('Error cargando API'));script.src=url.toString();document.body.appendChild(script);});}
async function loadPoints(){try{if(!CONFIG.API_URL){setStatus(els.api,'API no configurada','warn');renderPoints([]);return;}setStatus(els.api,'Consultando...','warn');const res=await jsonp({action:'get_points',dev_id:selectedDevice()});if(!res.ok)throw new Error(res.error||'Respuesta API inválida');setStatus(els.api,'OK','ok');renderPoints(res.points||[]);}catch(err){setStatus(els.api,'Error','bad');log('API get_points: '+err.message);}}
function appendRx(text){rxBuffer+=text;if(rxBuffer.length>16000)rxBuffer=rxBuffer.slice(-16000);log('RX '+text.replace(/\r?\n/g,' | '));for(const waiter of[...waiters]){const match=rxBuffer.match(waiter.regex);if(match){waiters=waiters.filter(w=>w!==waiter);clearTimeout(waiter.timer);waiter.resolve(match);}}}
function waitFor(regex,timeoutMs,label){return new Promise((resolve,reject)=>{const match=rxBuffer.match(regex);if(match){resolve(match);return;}const waiter={regex,resolve,reject,timer:null,label};waiter.timer=setTimeout(()=>{waiters=waiters.filter(w=>w!==waiter);reject(new Error('Timeout esperando '+label));},timeoutMs);waiters.push(waiter);});}
async function sendCommand(command){if(!bleRxChar)throw new Error('BLE no conectado');const data=enc.encode(command.trim()+'\r\n');log('TX '+command.trim());for(let i=0;i<data.length;i+=20){const chunk=data.slice(i,i+20);if(bleRxChar.writeValueWithoutResponse)await bleRxChar.writeValueWithoutResponse(chunk);else await bleRxChar.writeValue(chunk);await new Promise(r=>setTimeout(r,12));}}
async function sendAndWait(command,regex,timeoutMs,label){rxBuffer='';await sendCommand(command);return waitFor(regex,timeoutMs,label);}
async function connectBle(){try{setProcess('Buscando BLE...','warn');await disconnect(true);if(!('bluetooth'in navigator))throw new Error('Este navegador no soporta Web Bluetooth');bleDevice=await navigator.bluetooth.requestDevice({filters:[{namePrefix:'LoRaFieldLink'}],optionalServices:[NUS_SERVICE]});bleDevice.addEventListener('gattserverdisconnected',()=>{bleRxChar=null;bleTxChar=null;setStatus(els.ble,'Desconectado','warn');setJoined(-1);setProcess('BLE desconectado','warn');});const server=await bleDevice.gatt.connect();const service=await server.getPrimaryService(NUS_SERVICE);bleRxChar=await service.getCharacteristic(NUS_RX);bleTxChar=await service.getCharacteristic(NUS_TX);await bleTxChar.startNotifications();bleTxChar.addEventListener('characteristicvaluechanged',e=>appendRx(dec.decode(e.target.value)));setStatus(els.ble,'Conectado','ok');setProcess('BLE conectado. Verificando JOIN...','warn');await ensureJoined();}catch(err){setStatus(els.ble,'Error','bad');setProcess(err.message,'bad');log('BLE error: '+err.message);}finally{refreshActionState();}}
async function disconnect(silent=false){waiters.forEach(w=>{clearTimeout(w.timer);w.reject(new Error('Desconectado'));});waiters=[];if(bleDevice?.gatt?.connected)try{bleDevice.gatt.disconnect();}catch{}bleDevice=null;bleRxChar=null;bleTxChar=null;setStatus(els.ble,'Desconectado','warn');setJoined(-1);if(!silent)setProcess('Desconectado','warn');refreshActionState();}
async function ensureJoined(){try{setProcess('Consultando estado JOIN...','warn');const njs=await sendAndWait('AT+NJS=?',/AT\+NJS=([01])|\bNJS=([01])|\b([01])\s*\r?\n\s*OK/i,7000,'AT+NJS');const joined=Number(njs[1]||njs[2]||njs[3]);if(joined===1){setJoined(1);setProcess('Listo para tomar datos','ok');return true;}setProcess('No unido. Intentando JOIN...','warn');await sendCommand('AT+JOIN');await waitFor(/\+EVT:JOINED|AT\+NJS=1/i,CONFIG.JOIN_TIMEOUT_MS,'JOIN');setJoined(1);setProcess('JOIN exitoso. Listo para tomar datos','ok');return true;}catch(err){setJoined(0);setProcess('JOIN falló: '+err.message,'bad');log('JOIN falló: '+err.message);return false;}}
function readGps(){return new Promise((resolve,reject)=>{if(!('geolocation'in navigator)){reject(new Error('GPS no disponible'));return;}setStatus(els.gps,'Leyendo...','warn');navigator.geolocation.getCurrentPosition(pos=>{const c=pos.coords;const gps={timestamp:new Date(pos.timestamp).toISOString(),lat:c.latitude,lon:c.longitude,accuracy:c.accuracy,altitude:c.altitude,speed:c.speed,heading:c.heading};setStatus(els.gps,'OK ±'+Math.round(gps.accuracy)+' m','ok');els.lastAccuracy.textContent='±'+Math.round(gps.accuracy)+' m';resolve(gps);},err=>{setStatus(els.gps,'Error','bad');reject(err);},{enableHighAccuracy:true,timeout:15000,maximumAge:0});});}
function nextPayload(dev){const key='lfl-counter-'+dev;let n=Number(localStorage.getItem(key)||'0')+1;if(n>255)n=1;localStorage.setItem(key,String(n));const d=devNumber(dev).toString(16).padStart(2,'0').toUpperCase();const c=n.toString(16).padStart(2,'0').toUpperCase();return d+c;}
const LINKCHECK_RE=/\+EVT:LINKCHECK[:,]([\-\d]+)[:,]([\-\d]+)[:,]([\-\d]+)[:,]([\-\d]+)[:,]([\-\d]+)/;
function parseLinkCheck(match){return{result:Number(match[1]),demod_margin:Number(match[2]),gw_count:Number(match[3]),rssi:Number(match[4]),snr:Number(match[5]),raw:match[0]};}
async function takeSample(){if(measuring)return;measuring=true;refreshActionState();const dev=selectedDevice();try{setProcess('Leyendo GPS...','warn');const gps=await readGps();if(joinState!==1){const ok=await ensureJoined();if(!ok)throw new Error('No hay JOIN LoRaWAN');}const payload=nextPayload(dev);els.lastPayload.textContent=payload;setProcess('Solicitando LinkCheck...','warn');await sendAndWait('AT+LINKCHECK=1',/OK|AT_PARAM_ERROR|ERROR/i,8000,'OK de LINKCHECK');setProcess('Enviando uplink...','warn');rxBuffer='';await sendCommand('AT+SEND=2:'+payload);const match=await waitFor(LINKCHECK_RE,CONFIG.LINKCHECK_TIMEOUT_MS,'+EVT:LINKCHECK');const link=parseLinkCheck(match);if(link.result!==0)throw new Error('LinkCheck falló con código '+link.result);els.lastRssi.textContent=link.rssi;els.lastSnr.textContent=link.snr;els.lastGw.textContent=link.gw_count;setProcess('Guardando dato...','warn');const res=await jsonp({action:'save_sample',dev_id:dev,timestamp:new Date().toISOString(),lat:gps.lat,lon:gps.lon,accuracy_m:gps.accuracy,altitude:gps.altitude,speed:gps.speed,heading:gps.heading,join_state:'joined',rssi:link.rssi,snr:link.snr,gw_count:link.gw_count,payload});if(!res.ok)throw new Error(res.error||'No se pudo guardar');setProcess('Dato guardado','ok');await loadPoints();}catch(err){setProcess(err.message,'bad');log('Toma fallida: '+err.message);}finally{measuring=false;refreshActionState();}}
function initConfigState(){if(!CONFIG.API_URL){els.configWarning.classList.remove('hidden');setStatus(els.api,'API no configurada','warn');}else{setStatus(els.api,'Configurada','ok');}}
els.connect.onclick=connectBle;els.disconnect.onclick=()=>disconnect();els.retry.onclick=ensureJoined;els.take.onclick=takeSample;els.deviceSelect.onchange=()=>{localStorage.setItem('lfl-device',selectedDevice());loadPoints();safeInvalidate();};window.addEventListener('resize',safeInvalidate);window.addEventListener('orientationchange',()=>setTimeout(safeInvalidate,400));initDevices();initMap();initConfigState();loadPoints();refreshActionState();log('Aplicación lista. Selecciona dispositivo y conecta BLE.');
