// Copy this file as config.js for local testing.
// In GitHub Pages production, config.js can be generated by the deploy workflow
// from repository variables and secrets.
window.LFL_CONFIG = {
  // Google Apps Script Web App deployment URL ending in /exec.
  // Example: https://script.google.com/macros/s/AKfycbxxxxxxxxxxxxxxxx/exec
  API_URL: '',

  // Optional access token checked by Apps Script.
  // Warning: when used from a browser, this value is visible to users.
  API_TOKEN: '',

  // Device selector range shown in the web page.
  DEVICE_START: 1,
  DEVICE_END: 8,

  // Gateway reference point from the LoRaWAN class guide.
  GATEWAY_LAT: 3.341264,
  GATEWAY_LON: -76.529448,
  MAP_ZOOM: 17
};
